### ISSUE TITLE
[Kukkii Plugin] Kid Icarus: Uprising & The Legend of Zelda: Twilight Princess

### ISSUE THREAD

**Issue by FlameBeam** [IcySon55/Kuriimu#243] opened 2017-08-12 04:08 UTC
Console: 3DS
Format extension(s): bcres , jtex
Original game name: _Kid Icarus: Uprising, The Legend of Zelda: Twilight Princess._

First 8 byte of file(s):
Extension - [43 47 46 58 FF FE 14 00] - [CGFX]
Extension - [11 80 00 04 04 80 00 00] - [........]

More details?:
Bcres cannot be saved.
jtex cannot be opened.

Sample files (if possible):
https://mega.nz/#!1Q43SSqY!eO5tWpAENbhMg98dGjMTNYK-3OdgCXqFDkV3Aiu1l2o

**Comment by IcySon55** [comment] 2017-08-12 04:11
I specifically noted on new issues that you cannot attach files directly to issue on GitHub. Please remove them and provide links instead.

**Comment by FlameBeam** [comment] 2017-08-12 04:16
I'm sorry I ignore that.

**Comment by IcySon55** [comment] 2017-08-12 04:20
Closing the issue is not necessary, you can edit your original post. Actually I NEED you to edit your original post to remove the files because I can't do it.

**Comment by FlameBeam** [comment] 2017-08-12 04:27
Thanks you! I am edited my issue now.

**Comment by onepiecefreak3** [comment] 2017-08-12 10:00
jTEX - was compressed with LZ11. Added an exception if possibly compressed raw jTEX are provided.
Also added more image format identifiers for RawJTex.

CGFX - Added Save.

Issue closed.

**Closed by onepiecefreak3** 2017-08-12 10:00 UTC
