### ISSUE TITLE
.NDS files Batch import Issue

### ISSUE THREAD

**Issue by MetalFan1988** [IcySon55/Kuriimu#581] opened 2019-03-11 13:02 UTC
Issue: [bug report]
Console: NDS
Format extension(s): .nds
Type: [archive]
Game Name: .NDS files

First 8 bytes of the file(s):
<.nds> - [bytes in hex] - [bytes in ASCII]

More details:
<The Batch import option with any .NDS file leaves the output file in 0kb.>

Sample files (if possible):
<links>

**Comment by onepiecefreak3** [comment] 2021-05-29 22:46
This bug cannot be reproduced in Kuriimu2. This can be either due to having a certain bug fixed in the NDS plugin that caused this behaviour, or because of the rewrite of the batch import functionality. Please refer to Kuriimu2 if more issues regarding batch import come up.

**Closed by onepiecefreak3** 2021-05-29 22:46 UTC
Labels: Bug
