### ISSUE TITLE
Etrian Odyssey V Crashes when replacing Mori5.HPI/HPB

### ISSUE THREAD

**Issue by Shiriow** [IcySon55/Kuriimu#474] opened 2018-06-30 19:06 UTC
Issue: [bug report]
Console: N3DS XL
Format extension(s): HPI & HPB
Type: [archive]
Game Name: Etrian Odyssey V: Beyond the Myth | EUR | CTR-P-BMZP

First 8 bytes of the file(s):
MORI5.HPI - 48 50 49 48 00 00 00 00 - HPIH
MORI5.HPB - 41 43 4D 50 F8 02 00 00 - ACMP

More details:
Using the replace function of Karameru seems to make EOV either crash, or break the entire game.
For example, extracting and then replacing the whole file makes the game crash when booting it; replacing only the SKILL folder makes it crash when selecting the Skill tab inbattle or choosing to view the skilltrees and also makes enemies do nothing at all. 
This also happens even if only a MBM file has been editted, which has no relations to how skills work.

**Comment by IcySon55** [comment] 2018-06-30 19:11
I do recall making this plugin work for saving 1:1 so this is strange.

**Comment by Shiriow** [comment] 2018-06-30 19:21
Forgot to mention that the editted files are working correctly unpacked, problem is that running the game with unpacked MORI5 makes it lag badly, which is why I needed to do this.

**Comment by IcySon55** [comment] 2018-06-30 19:37
"unpacked", you mean uncompressed? This is starting to ring a bell. We don't have code to compress the files, only to decompress them last I recall. The game won't like that at all.

**Comment by Shiriow** [comment] 2018-06-30 19:44
Im not sure which word is it, but basically the edits work if I extract the MORI5, place everything on the romfs folder and edit the BuildMode file, which makes it work without the two MORI5 files.

**Comment by IcySon55** [comment] 2018-06-30 19:47
Oh, well that's not the optimal solution. So I wonder why the edited files don't work.

**Comment by Shiriow** [comment] 2018-06-30 19:48
Well its not just the edited files that don't work, even extracting something from the MORI5 and replacing the same exact files without any changes crashes the game

**Comment by IcySon55** [comment] 2018-06-30 19:49
I'll have to take a look at that, it's likely a bug/incompatibility in our RevLZ77 compression code.

**Comment by onepiecefreak3** [comment] 2018-07-02 19:07
The files get saved 1:1 if not changed.
So the crashes might occur due to your changes. Can you tell me what you did?
So what minimal effort do I need to reproduce a game crash?

**Comment by Shiriow** [comment] 2018-07-02 19:34
The game crashes even without my changes. 
I just tried it now again, I placed a fresh MORI5.HPI/HPB on my 3ds and the game loaded and didnt crash anywhere; 
then I tried extracting the Mori5 using Karameru(Extract MORI5.HPI option), 
replaced(Replace MORI5.HPI option) it with the just extracted files(without edits), 
saved to a new file, placed both on my 3DS and booting the game freezes it

**Comment by onepiecefreak3** [comment] 2018-07-03 17:40
All files are compressed and updated alright now. Even after extracting and reinjecting all files without edits the archive was still like the original. So issue fixed with newest commit;

**Closed by onepiecefreak3** 2018-07-03 17:40 UTC
