### ISSUE TITLE
EDIT: [Karameru] BG4 archive support

### ISSUE THREAD

**Issue by SteveDoido** [IcySon55/Kuriimu#373] opened 2017-11-21 20:11 UTC
Issue: plugin request | bug report
Console: 3DS
Format extension(s): msbt
Type: text
Game Name: Mario & Luigi - Superstar Saga + Bowser's Minions

First 8 byte of file(s):
<msbt> - [4D 73 67 53 74 64 42 6E] - [MsgStdBn]
<dat> - [42 47 34 00 04 01 0C 00] - [BG4.♦☺♀.]
<dat> - [42 47 34 00 04 01 A4 06] - [BG4.♦☺ñ♠]

More details:
<Of the .msbt files, only the "arena" one is properly read by Kuriimu>
<I'd like to request support for the two .dat files as well>

Sample files (if possible):
<https://mega.nz/#!WxVRXY5B!wvHYQ3QDc-M57_ot0znzwR1Eg3ksz0G2sA2TVwhBnSw>

**Comment by IcySon55** [comment] 2017-11-21 20:22
The MSBT issue is a duplicate of #336 and has been addressed in a newer build of the DLL.

In terms of BG4 support, my old editor can extract the files from those archives but cannot put them back together. We don't yet have an archive plugin for Karameru for BG4.

**Comment by SteveDoido** [comment] 2017-11-21 20:25
Any plans on:
1. Making this DLL the standart for compiled builds
2. Adding full BG4 compatibility
?

**Comment by IcySon55** [comment] 2017-11-21 20:35
It already is part of the build. The fix is in, but it's not released since v1.0.11 isn't a thing.
Like most formats, there is an intention to support them but only time will tell because we're working on a lot of background infrastructure right now and plugin development has slowed way down.

We're only three people with one of them being completely unavailable for the foreseeable future. It would be nice to attract some more developers that could concentrate on plugins while we're working out the backend and UI stuff.

**Comment by SteveDoido** [comment] 2017-11-21 21:17
Hum...
Might arrange that for you (can't guarantee it, though).

**Comment by onepiecefreak3** [comment] 2018-01-15 00:19
v1.0.11 is released and like already mentioned the MSBT was fixed as described.
The title was changed to represent current To-Do stuff.

**Comment by onepiecefreak3** [comment] 2018-01-15 15:51
And with the newest commit a Load/Save for BG4 archives was added.

**Closed by onepiecefreak3** 2018-01-15 15:51 UTC
Labels: Karameru
