### ISSUE TITLE
Error opening .XI files TSWTG

### ISSUE THREAD

**Issue by HucetJ** [IcySon55/Kuriimu#577] opened 2019-02-20 15:51 UTC
Issue: 99% of .XI files cannot be opened. Less than 1% can be opened.
Console: Nintendo Switch
Format extension(s): .XI
Type: Image
Game Name: The Snack World Trajers Gold (Not 3DS).

First 8 bytes of the file(s):
000 (2).xi - 49 4D 47 4E 30 30 00 00 - [IMGN00]

More details:
The Snack World Trejarer Gold video game on Switch has over 15000 pictures. Among these 15000 pictures and unlike the 3DS game, only a hundred can be opened.

Sample files (if possible):
https://drive.google.com/file/d/1PlwhUZ1I4oX77Oz8aOM3XEXi57-sJpOl/

Thank you.

**Comment by onepiecefreak3** [comment] 2019-02-20 16:03
I'm surprised that there can be some opened in the first place.

**Comment by HucetJ** [comment] 2019-02-20 16:13
Same here, I am using the latest version of Kuriimu which has been improved a lot regarding .xi files.
When I ran the software, only a hundred could have been only opened and thought the problem was coming from me.

Looking forward to the files to be compatible again soon.

**Comment by onepiecefreak3** [comment] 2019-02-20 21:14
Well switch XI were nevee supported in the first place. That's why I wonder why there are even some switch XIs opening

**Comment by HucetJ** [comment] 2019-02-21 13:50
Please find another sample of working and not working files:
https://drive.google.com/file/d/1j8q9g6_G1q8aXWWNxEqlLJ92rqN3IeGK/view?usp=sharing

Along with 3DS games, do you guys plan to support some Switch game as the .xi in the future ? It looks like a lot of switch games are already compatible with Kuriimu so it might just need a bit of adaptation here and there.

In any case, thank you for your time.

**Comment by onepiecefreak3** [comment] 2021-05-29 20:50
The newest dev build and upcoming Release 1.2.1 of Kuriimu2 have IMGN support now. Since it was ported, it received many updates and improvements, which may have this issue fixed already. Since the samples are unavailable and all IMGN samples I could gather do work, I will close this issue, since it is not reproducable (anymore) on mentioned versions of Kuriimu2.
Please refer to Kuriimu2 in the future, should you have more bug reports or requests.

**Closed by onepiecefreak3** 2021-05-29 20:50 UTC
Labels: Bug, Kukkii
