### ISSUE TITLE
G1T Nights of azure (Image and font)

### ISSUE THREAD

**Issue by Darkmet98** [IcySon55/Kuriimu#476] opened 2018-07-01 19:13 UTC
Issue: feature request
Console: PC
Format extension(s): g1t
Type:image
Game Name: Nights Of Azure

First 8 bytes of the file(s):
.g1t - 47 54 31 47 30 36 30 30 - GT1G0600

More details:
The actual plugin doesn't work with Nights Of Azure but scarlet and HyoutaTools works.
https://github.com/AdmiralCurtiss/HyoutaTools/blob/master/Gust/g1t/g1t.cs
https://github.com/xdanieldzd/Scarlet/blob/master/Scarlet.IO.ImageFormats/G1TG.cs

Sample files (if possible):
Font: https://drive.google.com/open?id=1Itb5T4tDeWG8LAD7n2jtKpcqjx6TFCxt
Random images: https://drive.google.com/open?id=1-h4QaG0d2aKOdxDasVhKphIlb2IC5Kl8

**Comment by Darkmet98** [comment] 2018-07-02 09:12
Ops, sorry, I forgot I am using this version from HyoutaTools
https://github.com/CatClawed/HyoutaTools/tree/master/Gust/g1t
Here is the compiled tool (from time ago) with the graphics exported
https://drive.google.com/open?id=15UiECR4K9hHA787Ei9oKUDVAeqnS5GHz

**Comment by onepiecefreak3** [comment] 2018-07-02 09:17
*I hate dds so much*
The problem is fixed in the newest commit. All images were openable and also savable in a form that was readable by Kukkii and was only different in image data, which is based on our encoders, but that shouldn't care ingame.
Have fun and closed.

**Closed by onepiecefreak3** 2018-07-02 09:17 UTC

**Comment by Darkmet98** [comment] 2018-07-02 10:02
Thanks! I exported a image and doesn't show in game
![imagen](https://user-images.githubusercontent.com/13910563/42158099-cc47d8e8-7def-11e8-808a-de2e233d7737.png)
